name: Linting and tests

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install Dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv sync --locked

      - name: Run Lint
        run: uvx ruff check

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout code"
        uses: actions/checkout@v4

      - name: "Run tests"
        run: make test
